"""Add parking and cnic records tables

Revision ID: 4f84caf17929
Revises: 342cbcb3e61c
Create Date: 2026-07-15 03:07:45.206628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f84caf17929'
down_revision: Union[str, Sequence[str], None] = '342cbcb3e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnic_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('country_of_stay', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_issue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_cnic_name_dob', 'cnic_records', ['name', 'date_of_birth'], unique=False)
    op.create_index('ix_cnic_number', 'cnic_records', ['cnic_number'], unique=False)
    op.create_index(op.f('ix_cnic_records_cnic_number'), 'cnic_records', ['cnic_number'], unique=False)
    op.create_table('parking_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=40), nullable=False),
    sa.Column('cnic_number', sa.String(length=15), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('entry_image_path', sa.String(length=500), nullable=True),
    sa.Column('exit_image_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parking_cnic', 'parking_records', ['cnic_number'], unique=False)
    op.create_index('ix_parking_entry_time', 'parking_records', ['entry_time'], unique=False)
    op.create_index('ix_parking_plate_status', 'parking_records', ['plate_number', 'status'], unique=False)
    op.create_index(op.f('ix_parking_records_cnic_number'), 'parking_records', ['cnic_number'], unique=False)
    op.create_index(op.f('ix_parking_records_id'), 'parking_records', ['id'], unique=False)
    op.create_index(op.f('ix_parking_records_plate_number'), 'parking_records', ['plate_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_records_plate_number'), table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_id'), table_name='parking_records')
    op.drop_index(op.f('ix_parking_records_cnic_number'), table_name='parking_records')
    op.drop_index('ix_parking_plate_status', table_name='parking_records')
    op.drop_index('ix_parking_entry_time', table_name='parking_records')
    op.drop_index('ix_parking_cnic', table_name='parking_records')
    op.drop_table('parking_records')
    op.drop_index(op.f('ix_cnic_records_cnic_number'), table_name='cnic_records')
    op.drop_index('ix_cnic_number', table_name='cnic_records')
    op.drop_index('ix_cnic_name_dob', table_name='cnic_records')
    op.drop_table('cnic_records')
    # ### end Alembic commands ###
