"""updated user model

Revision ID: 6565e981b90a
Revises: a0f649bb8f48
Create Date: 2026-06-28 06:34:12.449601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6565e981b90a'
down_revision: Union[str, Sequence[str], None] = 'a0f649bb8f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'camera_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cameras', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cameras', 'stream_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('face_detections', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.alter_column('face_detections', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('face_detections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('face_detections', 'full_frame_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('persons', 'flat_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('persons', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('persons', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('persons', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # Create gender enum type first
    gender_enum = postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender', create_type=True)
    gender_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='gender', create_type=False), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.alter_column('vehicle_detections', 'plate_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vehicle_detections', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.alter_column('vehicle_detections', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vehicle_detections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('vehicle_detections', 'full_frame_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('vehicles', 'flat_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('vehicles', 'color',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'color',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('vehicles', 'flat_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vehicle_detections', 'full_frame_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('vehicle_detections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('vehicle_detections', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vehicle_detections', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('vehicle_detections', 'plate_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    op.drop_column('users', 'phone_number')
    
    # Drop gender enum type
    gender_enum = postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender', create_type=False)
    gender_enum.drop(op.get_bind())
    op.alter_column('persons', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('persons', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('persons', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('persons', 'flat_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('face_detections', 'full_frame_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('face_detections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('face_detections', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('face_detections', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('cameras', 'stream_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('cameras', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('alerts', 'camera_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
