"""your migration message

Revision ID: 9c0daa999833
Revises: 4f84caf17929
Create Date: 2026-07-16 03:46:54.124250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0daa999833'
down_revision: Union[str, Sequence[str], None] = '4f84caf17929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_status', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('flat_no', sa.String(length=50), nullable=True),
    sa.Column('snapshot_url', sa.String(length=500), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    op.create_index('ix_access_logs_action_accessed', 'access_logs', ['action', 'accessed_at'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_plate_number'), 'access_logs', ['plate_number'], unique=False)
    op.create_index('ix_access_logs_status_accessed', 'access_logs', ['vehicle_status', 'accessed_at'], unique=False)
    op.create_unique_constraint(None, 'cnic_records', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cnic_records', type_='unique')
    op.drop_index('ix_access_logs_status_accessed', table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_plate_number'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index('ix_access_logs_action_accessed', table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_accessed_at'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
