"""surveillance core tables

Revision ID: a0f649bb8f48
Revises: b4581ff37aa6
Create Date: 2026-06-27 16:59:25.498735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'a0f649bb8f48'
down_revision: Union[str, Sequence[str], None] = 'b4581ff37aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('PLATE', 'FACE', 'BOTH', name='camera_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_code'), 'cameras', ['code'], unique=True)
    op.create_index(op.f('ix_cameras_is_active'), 'cameras', ['is_active'], unique=False)
    op.create_index('ix_cameras_type_active', 'cameras', ['type', 'is_active'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RESIDENT', 'STAFF', 'VISITOR', name='person_role'), nullable=False),
    sa.Column('flat_no', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_is_active'), 'persons', ['is_active'], unique=False)
    op.create_index(op.f('ix_persons_role'), 'persons', ['role'], unique=False)
    op.create_index('ix_persons_role_active', 'persons', ['role', 'is_active'], unique=False)
    op.create_index('ix_persons_validity', 'persons', ['valid_from', 'valid_until'], unique=False)
    op.create_table('face_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matched_person_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RESIDENT', 'VISITOR', 'STAFF', 'BLACKLIST', 'UNKNOWN', name='detection_status'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('full_frame_url', sa.String(length=500), nullable=False),
    sa.Column('action_taken', sa.Enum('OPEN_GATE', 'BLOCK', 'MARK_VISITOR', 'ALLOW', 'DENY', 'FLAG_UNKNOWN', 'REGISTER_VISITOR', name='action_type'), nullable=True),
    sa.Column('acted_by', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_detections_camera_detected', 'face_detections', ['camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_face_detections_camera_id'), 'face_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_face_detections_detected_at'), 'face_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_face_detections_status'), 'face_detections', ['status'], unique=False)
    op.create_index('ix_face_detections_status_detected', 'face_detections', ['status', 'detected_at'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_embeddings_person', 'face_embeddings', ['person_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_person_id'), 'face_embeddings', ['person_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('flat_no', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RESIDENT', 'VISITOR', 'STAFF', 'BLACKLIST', name='vehicle_status'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index('ix_vehicles_status_flat', 'vehicles', ['status', 'flat_no'], unique=False)
    op.create_table('vehicle_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('matched_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RESIDENT', 'VISITOR', 'STAFF', 'BLACKLIST', 'UNKNOWN', name='detection_status'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('full_frame_url', sa.String(length=500), nullable=False),
    sa.Column('action_taken', sa.Enum('OPEN_GATE', 'BLOCK', 'MARK_VISITOR', 'ALLOW', 'DENY', 'FLAG_UNKNOWN', 'REGISTER_VISITOR', name='action_type'), nullable=True),
    sa.Column('acted_by', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_detections_camera_detected', 'vehicle_detections', ['camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_camera_id'), 'vehicle_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_detected_at'), 'vehicle_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_plate_number'), 'vehicle_detections', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_status'), 'vehicle_detections', ['status'], unique=False)
    op.create_index('ix_vehicle_detections_status_detected', 'vehicle_detections', ['status', 'detected_at'], unique=False)
    op.create_table('visitor_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('face_detection_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='visitor_approval_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_approvals_created_at'), 'visitor_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_visitor_approvals_face_detection_id'), 'visitor_approvals', ['face_detection_id'], unique=True)
    op.create_index(op.f('ix_visitor_approvals_status'), 'visitor_approvals', ['status'], unique=False)
    op.create_index('ix_visitor_approvals_status_created', 'visitor_approvals', ['status', 'created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('BLACKLIST', 'UNKNOWN', 'TAILGATE', 'EXPIRED', name='alert_kind'), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_detection_id', sa.UUID(), nullable=True),
    sa.Column('face_detection_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='alert_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['face_detection_id'], ['face_detections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_detection_id'], ['vehicle_detections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_kind'), 'alerts', ['kind'], unique=False)
    op.create_index('ix_alerts_kind_created', 'alerts', ['kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_created', 'alerts', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index('ix_alerts_kind_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_kind'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_visitor_approvals_status_created', table_name='visitor_approvals')
    op.drop_index(op.f('ix_visitor_approvals_status'), table_name='visitor_approvals')
    op.drop_index(op.f('ix_visitor_approvals_face_detection_id'), table_name='visitor_approvals')
    op.drop_index(op.f('ix_visitor_approvals_created_at'), table_name='visitor_approvals')
    op.drop_table('visitor_approvals')
    op.drop_index('ix_vehicle_detections_status_detected', table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_status'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_plate_number'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_detected_at'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_camera_id'), table_name='vehicle_detections')
    op.drop_index('ix_vehicle_detections_camera_detected', table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    op.drop_index('ix_vehicles_status_flat', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_face_embeddings_person_id'), table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_person', table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index('ix_face_detections_status_detected', table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_status'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_detected_at'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_camera_id'), table_name='face_detections')
    op.drop_index('ix_face_detections_camera_detected', table_name='face_detections')
    op.drop_table('face_detections')
    op.drop_index('ix_persons_validity', table_name='persons')
    op.drop_index('ix_persons_role_active', table_name='persons')
    op.drop_index(op.f('ix_persons_role'), table_name='persons')
    op.drop_index(op.f('ix_persons_is_active'), table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_cameras_type_active', table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_active'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_code'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
