"""add user_id to complaints

Revision ID: add_user_id_to_complaints
Revises: complaint_table
Create Date: 2026-06-28 21:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_user_id_to_complaints'
down_revision: Union[str, Sequence[str], None] = 'complaint_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add user_id column to complaints table
    op.execute("""
        ALTER TABLE complaints 
        ADD COLUMN IF NOT EXISTS user_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'user_id')
    # ### end Alembic commands ###
