"""add complaint table

Revision ID: complaint_table
Revises: 6565e981b90a
Create Date: 2026-06-28 21:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'complaint_table'
down_revision: Union[str, Sequence[str], None] = '6565e981b90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create complaint_gender enum type using raw SQL with IF NOT EXISTS
    op.execute("DO $$ BEGIN CREATE TYPE complaint_gender AS ENUM ('male', 'female'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Create complaint_status enum type using raw SQL with IF NOT EXISTS
    op.execute("DO $$ BEGIN CREATE TYPE complaint_status AS ENUM ('Pending', 'In Progress', 'Resolved', 'Rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Create complaints table using raw SQL to avoid enum creation issues
    op.execute("""
        CREATE TABLE IF NOT EXISTS complaints (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            fullname VARCHAR(255) NOT NULL,
            gender complaint_gender NOT NULL,
            complaint_detail TEXT NOT NULL,
            tracking_id VARCHAR(20) NOT NULL UNIQUE,
            status complaint_status NOT NULL DEFAULT 'Pending',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
    """)
    
    # Create index
    op.execute("CREATE INDEX IF NOT EXISTS ix_complaints_tracking_id ON complaints (tracking_id);")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_tracking_id'), table_name='complaints')
    op.drop_table('complaints')
    
    # Drop complaint_status enum type
    complaint_status_enum = postgresql.ENUM('Pending', 'In Progress', 'Resolved', 'Rejected', name='complaint_status', create_type=False)
    complaint_status_enum.drop(op.get_bind())
    
    # Drop complaint_gender enum type
    complaint_gender_enum = postgresql.ENUM('male', 'female', name='complaint_gender', create_type=False)
    complaint_gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
