"""Add election, candidate, vote, and activity_log models

Revision ID: da7622c4648f
Revises: fix_complaint_status_enum
Create Date: 2026-06-29 21:53:05.474497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da7622c4648f'
down_revision: Union[str, Sequence[str], None] = 'fix_complaint_status_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('society_name', sa.String(length=255), nullable=False),
    sa.Column('society_location', sa.String(length=255), nullable=False),
    sa.Column('election_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_eligible_voters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('party', sa.String(length=255), nullable=False),
    sa.Column('p_class', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('voter_name', sa.String(length=255), nullable=False),
    sa.Column('voter_nic', sa.String(length=15), nullable=False),
    sa.Column('voter_block', sa.String(length=255), nullable=True),
    sa.Column('voter_phone', sa.String(length=20), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_voter_nic'), 'votes', ['voter_nic'], unique=True)
    op.alter_column('complaints', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('complaints', 'user_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('complaints', 'status',
               existing_type=postgresql.ENUM('Pending', 'In_Progress', 'Resolved', 'Rejected', name='complaint_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('complaints_tracking_id_key'), 'complaints', type_='unique')
    op.drop_index(op.f('ix_complaints_tracking_id'), table_name='complaints')
    op.create_index(op.f('ix_complaints_tracking_id'), 'complaints', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_tracking_id'), table_name='complaints')
    op.create_index(op.f('ix_complaints_tracking_id'), 'complaints', ['tracking_id'], unique=False)
    op.create_unique_constraint(op.f('complaints_tracking_id_key'), 'complaints', ['tracking_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('complaints', 'status',
               existing_type=postgresql.ENUM('Pending', 'In_Progress', 'Resolved', 'Rejected', name='complaint_status'),
               server_default=sa.text("'Pending'::complaint_status"),
               existing_nullable=False)
    op.alter_column('complaints', 'user_id',
               existing_type=sa.UUID(),
               server_default=sa.text("'00000000-0000-0000-0000-000000000000'::uuid"),
               existing_nullable=False)
    op.alter_column('complaints', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_votes_voter_nic'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('candidates')
    op.drop_table('elections')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
